version: 0.2

phases:
    build:
      commands:
        - echo "Building the application..."
        - apt-get update
        - apt-get -y install maven
        - mkdir /app
        - cp pom.xml /app
        - cd /app
        - mvn dependency:resolve
        - cp -r /code/* /app
        - mvn clean
        - mvn package -DskipTests
    post_build:
      commands:
        - GG easy
artifacts:
    files: /app/target/*.jar
    name: app

