version: 0.2

phases:
    build:
      commands:
        - mvn clean package
    post_build:
      commands:
        - echo Success
artifacts:
    files:
      - target/discovery-server.jar
    discard-paths: yes

