version: '3.7'
services:
  eureka-server:
    image: eureka-server
    ports:
      - "8080:8080"
  eureka-client:
    build: eureka-client
    ports:
      - "8082:8082"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8080/eureka